In [1]:
import pandas as pd
import numpy as np
import json
from pandas.api.types import is_numeric_dtype

# Load the CSV file
file_path = 'playoff_series.csv'
df = pd.read_csv(file_path)
print(df.columns)
# Rename the columns and divide PTS by 100

df = df.rename(columns={'PLAYER_ID': 'nba_id', 'PLAYER_NAME': 'player_name'})

# Select the specified columns
columns_to_keep = [
    'nba_id', 'player_name', 'year', 'round', 'OPP', 'USG_PCT', 'TS_PCT','TEAM_ID',
    'year_avg_ts', 'OPP_TS_PCT', 'rOPP_TS_PCT', 'GP', 'PTS', 'MIN', 'AGE',
    'AST_PCT', 'POSS', 'OFF_RATING', 'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A',
    'FG3_PCT', 'FTM', 'FTA', 'OREB', 'DREB', 'REB', 'AST', 'TOV', 'STL', 'BLK',
    'BLKA', 'PF', 'PFD', 'PLUS_MINUS'
]

df_selected = df[columns_to_keep].reset_index(drop=True)
print(df_selected[df_selected.player_name=='Stephen Curry']['PTS'])

# Create TSA column

# Function to safely divide
def safe_divide_num(a, b):
    if a==0 and b==0:
        return 0
    return np.where( (b != 0) &np.isfinite(b) & np.isfinite(a), a / b, 0)

# Function for weighted average
def safe_divide(a, b):
    result = pd.Series(0, index=a.index)
    mask = (b != 0) & np.isfinite(b) & np.isfinite(a)
    result[mask] = a[mask] / b[mask]
    return result
def weighted_average(group, value_col, weight_col):
    numerator = (group[value_col] * group[weight_col]).sum()
    denominator = group[weight_col].sum()
    

    wa = safe_divide_num(numerator, denominator)
    return wa

pct_col =[col for col in columns_to_keep if 'pct' in col.lower()]
sum_col=[col for col in columns_to_keep if is_numeric_dtype(df[col])==True]

sum_col = [col for col in sum_col if col not in ['nba_id','player_id','year','round','OPP']]
pct_col = [col for col in pct_col if col not in ['nba_id','player_id','year','round','OPP']]
sum_col=[col for col in sum_col if col not in pct_col]
id_col=['nba_id','player_name','year']


print(sum_col)
print(pct_col)
def weighted_frame(df,id_col,pct_col,sum_col):
    pct_df=[]
    for col in pct_col:
        new_columns =id_col.copy()
        new_columns.append(col)
        col_df= df.groupby(id_col).apply(weighted_average,col,'POSS').reset_index()
        col_df.columns=new_columns
        pct_df.append(col_df)

    df_grouped_pct = pct_df[0]
    for frame in pct_df[1:]:
        df_grouped_pct= df_grouped_pct.merge(frame)
    df_grouped_sum=df.groupby(id_col).sum()[sum_col].reset_index()


    df_grouped = df_grouped_pct.merge(df_grouped_sum,on=id_col)
    return df_grouped
df_grouped_year = weighted_frame(df_selected,id_col,pct_col,sum_col)

df_grouped_career = weighted_frame(df_selected,['nba_id','player_name'],pct_col,sum_col)
df_grouped_career['year']='Car'

df_grouped_career['OPP']='Career'
df_grouped_year['OPP']='All'

df_grouped_career['round']='Career'
df_grouped_year['round']='All'



df_final_with_career=pd.concat([df_selected,df_grouped_career,df_grouped_year])
df_final_with_career['TSA'] = df_final_with_career['FGA'] + 0.44 * df_final_with_career['FTA']


# Group by nba_id and year to roll up stats to the year

# Calculate derived statistics using safe division

zero_df = df_final_with_career[df_final_with_career.POSS==0]
df_final_with_career =  df_final_with_career[df_final_with_career.POSS!=0]
df_final_with_career['MPG'] = df_final_with_career['MIN'].divide(df_final_with_career['GP'])
df_final_with_career['PPG'] = df_final_with_career['PTS'].divide(df_final_with_career['GP'])
df_final_with_career['PTS/75'] = 75* df_final_with_career['PTS'].divide(df_final_with_career['POSS']) 
df_final_with_career['AST/75'] = 75* df_final_with_career['AST'].divide(df_final_with_career['POSS']) 
df_final_with_career['REB/75'] = 75* df_final_with_career['REB'].divide(df_final_with_career['POSS']) 
df_final_with_career['TOV/75'] = 75*df_final_with_career['TOV'].divide(df_final_with_career['POSS']) 
df_final_with_career['TSA/100'] = 100* (df_final_with_career['TSA']).divide(df_final_with_career['POSS'])
df_final_with_career['TS_ADD'] = df_final_with_career['TSA'] * df_final_with_career['rOPP_TS_PCT'] * 2
df_final_with_career['TS_ADD_1'] = df_final_with_career['TSA'] * (df_final_with_career['rOPP_TS_PCT'] + 0.01) * 2
df_final_with_career['TS_ADD_PER_100'] = 100*(df_final_with_career['TS_ADD'] ).divide(df_final_with_career['POSS'])
df_final_with_career['TS_ADD_1_PER_100'] = 100 * (df_final_with_career['TS_ADD_1']) / df_final_with_career['POSS']

extra_col = [col for col in df_final_with_career.columns if col not in zero_df]

for col in extra_col:
    zero_df[col]=0

df_final_with_career=pd.concat([df_final_with_career,zero_df])
# ... rest of the code remains the same

# Separate the rows for 'Career'
df_career = df_final_with_career[df_final_with_career['round'] == 'Career']

# Separate the rows for 'All'
df_all = df_final_with_career[df_final_with_career['round'] == 'All']

# Get the other rounds
df_rounds = df_final_with_career[(df_final_with_career['round'] != 'All')
                                 & (df_final_with_career['round'] != 'Career')]

# Create a dictionary to hold the nested structure
nested_data = []

for index, row in df_all.iterrows():
    nba_id = row['nba_id']
    year = row['year']

    # Get the rounds for this player and year
    rounds = df_rounds[(df_rounds['nba_id'] == nba_id)& (df_rounds['year'] == year)]

    # Convert the rounds to a list of dictionaries
    rounds_list = rounds.to_dict(orient='records')

    # Add the rounds to the 'All' row
    row['rounds'] = json.dumps(rounds_list)

    # Append to the nested data list
    nested_data.append(row)

# Convert the nested data list to a DataFrame
df_nested = pd.DataFrame(nested_data)

# Concatenate with the career rows
df_final_nested = pd.concat([df_nested, df_career], ignore_index=True)
df_final_nested=df_final_nested[df_final_nested['OPP_TS_PCT']>0]
# Save to CSV
output_path = 'playoffRTS.csv'
df_final_nested.to_csv(output_path, index=False)
for year in range(1997,2025):
    print(year)
    
    yrs_df = df_final_nested[df_final_nested.year==year]
    #print('Year Min TS')
    #print(yrs_df['TS_PCT'].min())
    print('Year Min OPP TS')
    print(yrs_df['OPP_TS_PCT'].min())
    #print('Year Max TS')
    #print(yrs_df['TS_PCT'].max())
    print('Year max OPP TS')
    print(yrs_df['OPP_TS_PCT'].max())

Index(['PLAYER_ID', 'PLAYER_NAME', 'NICKNAME', 'TEAM_ID', 'TEAM_ABBREVIATION',
       'AGE', 'GP', 'W', 'L', 'W_PCT',
       ...
       'REB_PCT_RANK', 'year', 'round', 'TEAM', 'OPP', 'OPP_ID', 'OPP_TS_PCT',
       'year_avg_ts', 'rOPP_TS_PCT', 'rTS_PCT'],
      dtype='object', length=131)
5665    146
5834    135
6047    161
6464    135
6604    147
6692    156
6729    156
6823     30
7004     69
7070    195
7124    158
7200    119
7365     98
7475    126
7515    134
7796     98
7871    175
7898    110
7988    148
8158    143
8247    146
8288    183
9184    140
9358    156
9454    119
9509    187
9586    236
9760    160
Name: PTS, dtype: int64
['TEAM_ID', 'year_avg_ts', 'GP', 'PTS', 'MIN', 'AGE', 'POSS', 'OFF_RATING', 'FGM', 'FGA', 'FG3M', 'FG3A', 'FTM', 'FTA', 'OREB', 'DREB', 'REB', 'AST', 'TOV', 'STL', 'BLK', 'BLKA', 'PF', 'PFD', 'PLUS_MINUS']
['USG_PCT', 'TS_PCT', 'OPP_TS_PCT', 'rOPP_TS_PCT', 'AST_PCT', 'FG_PCT', 'FG3_PCT']
1997
Year Min OPP TS
50.935941018056596
Year max OPP TS
54.50782950036268
1998
Year Min OPP TS
48.24676174277116
Year max OPP TS
54.51211380306736
1999
Year Min OPP TS
46.37538326763031
Year max OPP TS
51.750310501863005
2000
Year Min OPP TS
49.01440163133521
Year max OPP TS
54.364047243423016
2001
Year Min OPP TS
48.28912292968579
Year max OPP TS
53.135207250310536
2002
Year Min OPP TS
50.19630435710323
Year max OPP TS
53.0439897483299
2003
Year Min OPP TS
48.86260983821958
Year max OPP TS
53.42796226991397
2004
Year Min OPP TS
48.00683371298404
Year max OPP TS
53.459231687699706
2005
Year Min OPP TS
50.243259218842354
Year max OPP TS
54.15041033230189
2006
Year Min OPP TS
50.14003071641521
Year max OPP TS
54.206802103661424
2007
Year Min OPP TS
51.067833499591906
Year max OPP TS
55.63895854593272
2008
Year Min OPP TS
50.743502625424696
Year max OPP TS
55.24861878453039
2009
Year Min OPP TS
50.85110967463908
Year max OPP TS
54.82456140350877
2010
Year Min OPP TS
51.78672347085162
Year max OPP TS
54.2740841248304
2011
Year Min OPP TS
50.91229478943612
Year max OPP TS
55.38903328582209
2012
Year Min OPP TS
49.168832257462384
Year max OPP TS
54.16399058017555
2013
Year Min OPP TS
49.52387192591621
Year max OPP TS
54.76833623294571
2014
Year Min OPP TS
50.05205847902476
Year max OPP TS
55.517002081887576
2015
Year Min OPP TS
50.96935584740463
Year max OPP TS
54.16577195619497
2016
Year Min OPP TS
51.36910554719986
Year max OPP TS
56.210325387313
2017
Year Min OPP TS
52.460566553999676
Year max OPP TS
56.084722396290275
2018
Year Min OPP TS
53.193743907091076
Year max OPP TS
57.24498506188647
2019
Year Min OPP TS
53.26095431155465
Year max OPP TS
56.16300140021415
2020
Year Min OPP TS
52.55109941158253
Year max OPP TS
56.6390041493776
2021
Year Min OPP TS
53.75265754743472
Year max OPP TS
57.87183045288255
2022
Year Min OPP TS
53.77506072207814
Year max OPP TS
57.7105404179892
2023
Year Min OPP TS
55.30066380320188
Year max OPP TS
59.36161930712339
2024
Year Min OPP TS
55.03366528242552
Year max OPP TS
59.36388779138681

In [4]:
for year in range(1997,2025):
    print(year)
    
    yrs_df = df_selected[df_selected.year==year]
    #print('Year Min TS')
    #print(yrs_df['TS_PCT'].min())
    print('Year Min OPP TS')
    print(yrs_df['OPP_TS_PCT'].min())
    #print('Year Max TS')
    #print(yrs_df['TS_PCT'].max())
    print('Year max OPP TS')
    print(yrs_df['OPP_TS_PCT'].max())

1997
Year Min OPP TS
50.9359410180566
Year max OPP TS
54.665523909985936
1998
Year Min OPP TS
48.24676174277116
Year max OPP TS
54.51211380306735
1999
Year Min OPP TS
46.37538326763031
Year max OPP TS
52.13455520786767
2000
Year Min OPP TS
49.01440163133522
Year max OPP TS
54.364047243423016
2001
Year Min OPP TS
48.28912292968579
Year max OPP TS
53.135207250310536
2002
Year Min OPP TS
49.48383710248896
Year max OPP TS
53.93357833129168
2003
Year Min OPP TS
48.86260983821959
Year max OPP TS
53.76169438669438
2004
Year Min OPP TS
48.00683371298405
Year max OPP TS
53.7795040334628
2005
Year Min OPP TS
50.24325921884236
Year max OPP TS
54.15041033230189
2006
Year Min OPP TS
50.14003071641522
Year max OPP TS
55.003785685654485
2007
Year Min OPP TS
51.06783349959191
Year max OPP TS
56.25992191187197
2008
Year Min OPP TS
50.743502625424696
Year max OPP TS
55.24861878453039
2009
Year Min OPP TS
50.85110967463908
Year max OPP TS
55.216268277734
2010
Year Min OPP TS
51.786723470851626
Year max OPP TS
54.2740841248304
2011
Year Min OPP TS
50.91229478943612
Year max OPP TS
55.38903328582209
2012
Year Min OPP TS
48.65616311399444
Year max OPP TS
54.16399058017555
2013
Year Min OPP TS
49.52387192591622
Year max OPP TS
54.7683362329457
2014
Year Min OPP TS
50.052058479024765
Year max OPP TS
55.517002081887576
2015
Year Min OPP TS
50.96935584740463
Year max OPP TS
54.16577195619497
2016
Year Min OPP TS
51.369105547199865
Year max OPP TS
56.210325387313
2017
Year Min OPP TS
52.46056655399968
Year max OPP TS
56.08472239629027
2018
Year Min OPP TS
53.19374390709108
Year max OPP TS
57.24498506188647
2019
Year Min OPP TS
53.260954311554656
Year max OPP TS
56.22039652932054
2020
Year Min OPP TS
52.55109941158253
Year max OPP TS
56.65183276730297
2021
Year Min OPP TS
53.75265754743472
Year max OPP TS
58.11943212789327
2022
Year Min OPP TS
53.77506072207814
Year max OPP TS
58.10400775422478
2023
Year Min OPP TS
55.30066380320188
Year max OPP TS
59.63441728943647
2024
Year Min OPP TS
55.03366528242552
Year max OPP TS
59.3638877913868

In [5]:
df_final_nested

,nba_id,player_name,year,round,OPP,USG_PCT,TS_PCT,TEAM_ID,year_avg_ts,OPP_TS_PCT,...,PTS/75,AST/75,REB/75,TOV/75,TSA/100,TS_ADD,TS_ADD_1,TS_ADD_PER_100,TS_ADD_1_PER_100,rounds
0,2,Byron Scott,1997,All,All,0.16594444444444448,58.6,3221225494,107.154334,52.819041081931445,...,15.178571,3.273810,3.571429,2.380952,16.412698,478.200922,479.028122,189.762271,190.090524,"[{""nba_id"": 2, ""player_name"": ""Byron Scott"", ""..."
1,3,Grant Long,1997,All,All,0.135,54.7,1610612765,53.577167,50.98316529038733,...,12.096774,1.451613,5.322581,0.000000,14.735484,169.78501,170.24181,109.538716,109.833426,"[{""nba_id"": 3, ""player_name"": ""Grant Long"", ""y..."
2,3,Grant Long,1999,All,All,0.17647770700636944,47.23710191082803,3221225474,102.228624,50.15738079417528,...,12.539809,0.955414,8.837580,2.746815,17.095541,-627.042282,-624.895082,-99.847497,-99.505586,"[{""nba_id"": 3, ""player_name"": ""Grant Long"", ""y..."
3,3,Grant Long,2003,All,All,0.06743076923076922,18.955384615384617,3221225476,103.803455,50.52134213603061,...,2.307692,1.153846,5.769231,1.153846,6.153846,-252.52766,-252.44766,-388.504093,-388.381016,"[{""nba_id"": 3, ""player_name"": ""Grant Long"", ""y..."
4,7,Dan Schayes,1997,All,All,0.156,44.4,1610612753,53.577167,51.19943124483992,...,9.593023,2.180233,5.232558,1.744186,14.395349,-336.707835,-336.212635,-195.760369,-195.472462,"[{""nba_id"": 7, ""player_name"": ""Dan Schayes"", ""..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7188,1641753,Chris Livingston,Car,Career,Career,0.154,43.1,1610612749,58.035355,59.36388779138681,...,12.500000,0.000000,0.000000,0.000000,19.333333,-75.464439,-75.418039,-628.870328,-628.483661,NaN
7189,1641765,Olivier-Maxence Prosper,Car,Career,Career,0.11105882352941177,0.0,3221225484,116.070710,55.161931078696604,...,0.000000,4.411765,13.235294,0.000000,11.764706,-220.647724,-220.607724,-1297.92779,-1297.692496,NaN
7190,1641767,Ben Sheppard,Car,Career,Career,0.11010846953937592,58.03789004457652,4831838262,174.106064,56.73628271378458,...,9.806835,1.894502,5.683507,1.225854,11.138187,195.136971,196.636171,28.995092,29.217856,NaN
7191,1641775,Jordan Walsh,Car,Career,Career,0.1238695652173913,47.82608695652174,3221225476,116.070710,57.42570440138734,...,6.521739,0.000000,6.521739,0.000000,13.043478,-57.597705,-57.537705,-250.424803,-250.163933,NaN
7192,1641816,Hunter Tyson,Car,Career,Career,0.182,10.2,1610612743,58.035355,55.21796839354598,...,2.678571,2.678571,8.035714,2.678571,17.428571,-439.375372,-439.277772,-1569.197755,-1568.849184,NaN

In [6]:
df_final_nested['rounds']

0       [{"nba_id": 2, "player_name": "Byron Scott", "...
1       [{"nba_id": 3, "player_name": "Grant Long", "y...
2       [{"nba_id": 3, "player_name": "Grant Long", "y...
3       [{"nba_id": 3, "player_name": "Grant Long", "y...
4       [{"nba_id": 7, "player_name": "Dan Schayes", "...
                              ...
7188                                                  NaN
7189                                                  NaN
7190                                                  NaN
7191                                                  NaN
7192                                                  NaN
Name: rounds, Length: 7186, dtype: object

In [7]:
df_final_nested[df_final_nested.player_name.str.contains('Shaq')]

,nba_id,player_name,year,round,OPP,USG_PCT,TS_PCT,TEAM_ID,year_avg_ts,OPP_TS_PCT,...,PTS/75,AST/75,REB/75,TOV/75,TSA/100,TS_ADD,TS_ADD_1,TS_ADD_PER_100,TS_ADD_1_PER_100,rounds
588,406,Shaquille O'Neal,1997,All,All,0.35495563139931746,54.99488054607509,3221225494,107.154334,52.808561591608864,...,30.972696,3.711604,12.158703,2.815700,37.406143,958.48223,962.86623,163.56352,164.311643,"[{""nba_id"": 406, ""player_name"": ""Shaquille O'N..."
589,406,Shaquille O'Neal,1998,All,All,0.34138876889848807,60.55313174946005,4831838241,157.003868,51.658705122616965,...,32.073434,3.077754,10.691145,3.482721,35.416847,5834.032313,5840.591513,630.025088,630.733425,"[{""nba_id"": 406, ""player_name"": ""Shaquille O'N..."
590,406,Shaquille O'Neal,1999,All,All,0.31362969004893965,51.403915171288745,3221225494,102.228624,48.1616188069652,...,26.060359,2.202284,11.378467,2.202284,33.755302,1341.791927,1345.930327,218.889385,219.564491,"[{""nba_id"": 406, ""player_name"": ""Shaquille O'N..."
591,406,Shaquille O'Neal,2000,All,All,0.3114872611464969,55.54564755838641,6442450988,209.288299,50.75715391042931,...,28.144904,2.826433,14.132166,2.229299,33.717622,6083.68541,6096.39021,322.913238,323.587591,"[{""nba_id"": 406, ""player_name"": ""Shaquille O'N..."
592,406,Shaquille O'Neal,2001,All,All,0.3207256097560976,56.27019817073171,6442450988,207.076799,49.781863424132744,...,27.839177,2.915396,14.119665,3.258384,32.926829,5605.921221,5614.561221,427.280581,427.939117,"[{""nba_id"": 406, ""player_name"": ""Shaquille O'N..."
593,406,Shaquille O'Neal,2002,All,All,0.3126738690074274,56.758001350438896,6442450988,207.993312,50.554467848751926,...,27.397029,2.734639,12.103309,3.139770,32.108035,5899.808501,5909.318901,398.366543,399.008704,"[{""nba_id"": 406, ""player_name"": ""Shaquille O'N..."
594,406,Shaquille O'Neal,2003,All,All,0.29510839532412325,57.057598299681196,3221225494,103.803455,50.48428159857757,...,25.823592,3.506908,14.187035,2.789586,30.189160,3734.695617,3740.377217,396.885825,397.489609,"[{""nba_id"": 406, ""player_name"": ""Shaquille O'N..."
595,406,Shaquille O'Neal,2004,All,All,0.24707286729857822,56.129087677725124,6442450988,206.319926,48.68929345323732,...,21.015995,2.443720,12.929502,2.443720,24.808057,6230.976459,6239.351659,369.133676,369.629838,"[{""nba_id"": 406, ""player_name"": ""Shaquille O'N..."
596,406,Shaquille O'Neal,2005,All,All,0.30647322540473226,55.436612702366126,4831838244,158.838676,51.775145923475414,...,23.536737,2.334994,9.526775,3.922790,28.348692,1666.992595,1671.545395,207.595591,208.162565,"[{""nba_id"": 406, ""player_name"": ""Shaquille O'N..."
597,406,Shaquille O'Neal,2006,All,All,0.2841037868162693,56.770546984572235,6442450992,214.173355,52.204900746802124,...,22.300140,2.051192,11.833801,4.470547,26.022440,3388.440012,3395.861612,237.618514,238.138963,"[{""nba_id"": 406, ""player_name"": ""Shaquille O'N..."
598,406,Shaquille O'Neal,2007,All,All,0.335,52.900000000000006,1610612748,54.190751,52.03941236518573,...,24.779736,1.651982,11.233480,4.625551,31.224670,121.996903,123.414503,53.743129,54.367623,"[{""nba_id"": 406, ""player_name"": ""Shaquille O'N..."
599,406,Shaquille O'Neal,2008,All,All,0.267,48.6,1610612756,54.024444,51.71469016850085,...,19.000000,1.250000,11.500000,2.250000,26.053333,-486.888367,-485.325167,-162.296122,-161.775056,"[{""nba_id"": 406, ""player_name"": ""Shaquille O'N..."
600,406,Shaquille O'Neal,2010,All,All,0.25947807933194156,55.69164926931107,3221225478,108.607881,53.00108120933803,...,19.885177,2.348643,9.551148,3.757829,23.732777,611.727554,614.001154,127.709301,128.183957,"[{""nba_id"": 406, ""player_name"": ""Shaquille O'N..."
601,406,Shaquille O'Neal,2011,All,All,0.13,34.7,1610612738,54.152536,51.80495925698764,...,7.142857,3.571429,0.000000,0.000000,13.714286,-98.524565,-98.466965,-469.164597,-468.890311,"[{""nba_id"": 406, ""player_name"": ""Shaquille O'N..."
5037,1627885,Shaquille Harrison,2021,All,All,0.09765517241379311,86.02298850574712,3221225486,114.316544,57.777294255895264,...,7.758621,2.586207,6.896552,4.310345,6.114943,300.534187,300.640587,345.441594,345.563893,"[{""nba_id"": 1627885, ""player_name"": ""Shaquille..."
5038,1627885,Shaquille Harrison,2023,All,All,0.12117241379310345,61.41896551724138,4831838241,174.319728,57.49254529018978,...,12.931034,11.637931,3.879310,0.000000,13.586207,61.880383,62.037983,106.690315,106.962039,"[{""nba_id"": 1627885, ""player_name"": ""Shaquille..."
5812,406,Shaquille O'Neal,Car,Career,Career,0.3007992433199338,55.98200520217547,59592671631,1944.856262,50.73161052294018,...,25.650272,2.660203,12.402459,3.085836,30.456373,40575.050081,40652.330081,319.815954,320.425081,NaN
6892,1627885,Shaquille Harrison,Car,Career,Career,0.10706206896551725,76.18137931034482,8053063727,288.636272,57.66339466961306,...,9.827586,6.206897,5.689655,2.586207,9.103448,488.874795,489.138795,337.155031,337.3371,NaN